### ISSUE TITLE
Registrar aplicación 

### ISSUE THREAD

**Issue by yquispeb** [Demner21/track-system-demo#2]
Se esta ingresando los datos y la aplicación me indica que existe, he validado en la consola del firebase y no existe, es un error que ya te había indicado por favor apóyame con la solución.

![image](https://user-images.githubusercontent.com/84193046/123352761-a0032900-d525-11eb-8ed3-af812626bd50.png)

Listado
![image](https://user-images.githubusercontent.com/84193046/123352798-b7421680-d525-11eb-916e-ed899e59a280.png)

**Comment by Demner21** [comment]
Se corrigió
![imagen](https://user-images.githubusercontent.com/18225600/124211832-6b5a1900-dab3-11eb-96e2-035aa0226fe5.png)

Se adjunta evidencia
![imagen](https://user-images.githubusercontent.com/18225600/124211867-7c0a8f00-dab3-11eb-8c05-62ac94b41aa6.png)

**Comment by Demner21** [comment]
Corregido con el commit 4018fad92ca7206ff6b21269659eaa8ac43f3257
