### ISSUE TITLE
Registro de Transacción 

### ISSUE THREAD

**Issue by yquispeb** [Demner21/track-system-demo#4]
en el Registro de las transacción no se puede registrar todas existen
![image](https://user-images.githubusercontent.com/84193046/123368830-2463a500-d542-11eb-90b6-1401b608b864.png)

el listado aun no se ven los botones de mantenimiento
![image](https://user-images.githubusercontent.com/84193046/123368881-3e9d8300-d542-11eb-871a-e0fd0dc8e37a.png)

**Comment by Demner21** [comment]
Corregido
![imagen](https://user-images.githubusercontent.com/18225600/124214881-95faa080-dab8-11eb-988e-213dfe427bf3.png)

corregido en el commit  c5290ac
