### ISSUE TITLE
Registro de Trazabilidad 

### ISSUE THREAD

**Issue by yquispeb** [Demner21/track-system-demo#5]
![image](https://user-images.githubusercontent.com/84193046/125171004-71b55880-e177-11eb-9f3e-fcc85a495672.png)

cuando se cambia la selección del combo aplicación por segunda vez el combo de transacción ya no muestra el seleccione 
en el adjuntar documentación parece un label por favor que se vea como un botón.

**Comment by Demner21** [comment]
corregido en commit 8907792
