### ISSUE TITLE
Registro de Trazabilidad 

### ISSUE THREAD

**Issue by yquispeb** [Demner21/track-system-demo#6]
![image](https://user-images.githubusercontent.com/84193046/125171214-8e05c500-e178-11eb-89c2-10fd7fd7ea9f.png)

Debería de mostrar un botón para quitar el registro en caso de error por parte del usuario.

**Comment by Demner21** [comment]
Corregido en commi f668d21
![imagen](https://user-images.githubusercontent.com/18225600/125549580-ce5bc92d-fa16-411b-9af2-da8c3e9a1eb9.png)
