### ISSUE TITLE
Registro de Trazabilidad de insumos

### ISSUE THREAD

**Issue by yquispeb** [Demner21/track-system-demo#7]
![image](https://user-images.githubusercontent.com/84193046/125171309-33b93400-e179-11eb-95aa-60068fa6b723.png)

1. Después de agregar el insumo el combo debe de volver a seleccione
2. en el listado de insumo debe de tener la opción de quitar el registro antes de guardar

**Comment by Demner21** [comment]
punto 2 corregido en commit: b2af7ec
![imagen](https://user-images.githubusercontent.com/18225600/125553110-5f9c86bc-8c23-4b02-a79d-41b8da0507b3.png)
