### ISSUE TITLE
Registro de Insumo

### ISSUE THREAD

**Issue by yquispeb** [Demner21/track-system-demo#8]
![image](https://user-images.githubusercontent.com/84193046/125171458-f3a68100-e179-11eb-86a7-ee472da3ceb4.png)

No muestra el mensaje de registro exitoso

**Comment by Demner21** [comment]
Corregido en el commit  2358ab4
![imagen](https://user-images.githubusercontent.com/18225600/125332377-9859c780-e30e-11eb-9964-34b0738fbb72.png)
